# Site settings
author: Ting
title: Journeys of a Wanderlust Heroine
header-img: img/home-bg.png
email: ttzhenng@gmail.com
copyright_name: Ting
description: > # this means to ignore newlines until "baseurl:"
  Many steps become a mile, and many miles add up to an adventure
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tagting

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
